### ISSUE TITLE
error while using VikiTasks

### ISSUE THREAD

**Issue by Garonenur** [tomtom/vikitasks_vim#10]
when using :VikiTasks and select one of the tasks to jump to its location in my viki-files I get the following error:
```
Error detected while processing function vikitasks#Tasks..<SNR>103_TasksList..<SNR>103_FilterTasks:
line   16:
E872: (NFA regexp) Too many '('
E51: Too many \(
Error detected while processing function vikitasks#Tasks..<SNR>103_TasksList..<SNR>103_SortTasks..<SNR>103_GetTaskDu
eDate:
line    1:
E872: (NFA regexp) Too many '('
E51: Too many \(
```
where the last two lines of error repeat seemingly endlessly.
Any idea what's wrong or how I can help debug this?

**Comment by Garonenur** [comment]
might not be the problem here, but I also get a deprecated warning when calling VikiTask:
```
trag#Grep() is deprecated. Please use trag#GrepWithArgs() instead.
```

**Comment by tomtom** [comment]
With respect to the "deprecated" message, please also update trag_vim.

**Comment by Garonenur** [comment]
thanks, and done.
now the highlighting only works on non indented tasks?
