### ISSUE TITLE
The tasks window not open

### ISSUE THREAD

**Issue by darkprof83** [tomtom/vikitasks_vim#12]
If run `:VikiTasks!` or `:VikiTasks *` or etc the tasks window not open.
![_2017-10-23_19-13-18](https://user-images.githubusercontent.com/4998392/31893917-4b4904b8-b826-11e7-82bb-f209a783670d.png)

**Comment by tomtom** [comment]
Erm, I simply assume you're using vikibase_vim instead of viki_vim now. It seems vikitasks_vim doesn't work with vikibase_vim yet and relies on viki_vim for support for viki markup. I didn't realise that since I now use ttodo_txt (a variant of the todo.txt format) for managing my todos.

**Comment by darkprof83** [comment]
Yes I am using vikibase_vim.
 In readme of vikibase_vim written
`Optional enhancements~
- vikitasks (vimscript #2894): Distributed TODO lists (discontinued plugin)`

**Comment by tomtom** [comment]
> `Optional enhancements~

Could you please update vikibase & vikitaks and test if it works now?

**Comment by darkprof83** [comment]
Yes, I am updated plugins and see this error
`Error detected while processing function vikitasks#Tasks[3]..<SNR>77_GetTasks:
line   91:
E605: Exception not caught: VikiTasks: No task files`

**Comment by tomtom** [comment]
In its current form, you have to define at least one interviki.

**Comment by darkprof83** [comment]
I am added filename to g:vikitasks#files, but window not open. Run without errors.

**Comment by tomtom** [comment]
The task lines must be indented by at least one whitespace character. In viki markup, the type of text a line represents is most of the time determined by the prefix of that line. Indented lines (leading whitespace) usually identifies lists or tasks.

**Comment by darkprof83** [comment]
Thanks you, problem solved!
